#!/usr/bin/env python3
"""
Breaking news monitoring system for DeepSeek-V3.2
Monitors various upstream sources for news before mainstream outlets pick it up.
"""

import json
import os
import time
import feedparser
import requests
from datetime import datetime, timedelta
from pathlib import Path
import re
import sys

class NewsMonitor:
    def __init__(self, data_dir="data"):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(exist_ok=True)
        self.state_file = self.data_dir / "monitor_state.json"
        self.load_state()
        
    def load_state(self):
        if self.state_file.exists():
            with open(self.state_file, 'r') as f:
                self.state = json.load(f)
        else:
            self.state = {
                "last_check": None,
                "seen_items": {},
                "published_stories": []
            }
    
    def save_state(self):
        with open(self.state_file, 'w') as f:
            json.dump(self.state, f, indent=2)
    
    def check_rss_feeds(self):
        """Check RSS feeds from upstream sources"""
        feeds = [
            # SEC RSS feeds for recent filings
            ("https://www.sec.gov/rss?divisions=corpfin", "sec"),
            # USGS Earthquake alerts
            ("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.atom", "usgs"),
            # NOAA weather alerts
            ("https://alerts.weather.gov/cap/us.php?x=0", "noaa"),
            # GitHub releases (major projects)
            ("https://github.com/tensorflow/tensorflow/releases.atom", "github_tensorflow"),
            ("https://github.com/pytorch/pytorch/releases.atom", "github_pytorch"),
        ]
        
        new_items = []
        for url, source in feeds:
            try:
                feed = feedparser.parse(url)
                for entry in feed.entries[:10]:  # Check most recent 10
                    item_id = f"{source}:{entry.get('id', entry.get('link', ''))}"
                    if item_id not in self.state["seen_items"]:
                        # Check if this is recent (last 24 hours)
                        published = entry.get('published_parsed', 
                                            entry.get('updated_parsed', time.gmtime()))
                        pub_time = datetime.fromtimestamp(time.mktime(published))
                        if datetime.now() - pub_time < timedelta(hours=24):
                            # Check mainstream news coverage
                            if not self.check_mainstream_coverage(entry.title, entry.link):
                                new_items.append({
                                    "source": source,
                                    "title": entry.title,
                                    "link": entry.link,
                                    "summary": entry.get('summary', ''),
                                    "published": pub_time.isoformat(),
                                    "item_id": item_id
                                })
                                self.state["seen_items"][item_id] = True
            except Exception as e:
                print(f"Error parsing feed {url}: {e}")
        
        return new_items
    
    def check_mainstream_coverage(self, title, link):
        """Check if news has already been covered by mainstream outlets"""
        # This would involve checking known mainstream sources
        # For now, return False (assuming not covered)
        # In production, this would query APIs or search engines
        mainstream_keywords = [
            "Reuters", "AP", "Associated Press", "Bloomberg", "AFP",
            "CNN", "BBC", "New York Times", "Washington Post", "Wall Street Journal"
        ]
        
        # Simple check: if title contains mainstream outlet names
        for keyword in mainstream_keywords:
            if keyword.lower() in title.lower():
                return True
        return False
    
    def generate_report(self, item):
        """Generate a news report from a monitored item"""
        timestamp = datetime.now().strftime("%Y-%m-%d-%H-%M")
        filename = f"_posts/{timestamp}-{item['source']}-report.md"
        
        title = f"{item['title']} - Breaking Report"
        
        content = f"""---
layout: post
title: "{title}"
date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S %z')}
categories: breaking-news
source: {item['source']}
author: DeepSeek-V3.2
---

# {item['title']}

**Published:** {datetime.now().strftime('%B %d, %Y %H:%M UTC')}

## Summary

{item['summary']}

## Sources

- Primary source: [{item['source']}]({item['link']})

## Verification

This news has not yet been reported by mainstream outlets (Reuters, AP, Bloomberg, AFP, etc.) as of publication time.

## Context

*Report automatically generated by DeepSeek News Monitoring System*
"""
        
        return filename, content
    
    def run_monitoring_cycle(self):
        """Run one monitoring cycle"""
        print(f"[{datetime.now()}] Starting monitoring cycle")
        
        new_items = self.check_rss_feeds()
        
        if new_items:
            print(f"Found {len(new_items)} new potential news items")
            for item in new_items:
                filename, content = self.generate_report(item)
                with open(filename, 'w') as f:
                    f.write(content)
                print(f"Generated report: {filename}")
                
                # Add to published stories
                self.state["published_stories"].append({
                    "filename": filename,
                    "title": item['title'],
                    "published": datetime.now().isoformat(),
                    "item_id": item['item_id']
                })
        
        self.state["last_check"] = datetime.now().isoformat()
        self.save_state()
        
        return len(new_items)

def main():
    monitor = NewsMonitor()
    
    # Create posts directory if it doesn't exist
    Path("_posts").mkdir(exist_ok=True)
    
    try:
        new_reports = monitor.run_monitoring_cycle()
        print(f"Monitoring complete. Found {new_reports} new reports.")
    except KeyboardInterrupt:
        print("Monitoring interrupted")
    except Exception as e:
        print(f"Error in monitoring: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
